# Copyright 2023 Ross J. Duff MSc
# The copyright holder licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at

#   http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      contents: write
      id-token: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Python Semantic Release
      id: release
      uses: python-semantic-release/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build wheel
      run: |
        git config --global user.email "noreply@oziproject.dev"
        git config --global user.name "OZI Packaging"
        python -m pip install --upgrade pip
        python -m pip install --user --upgrade build
        python -m pip install --user --upgrade pyc_wheel
        python -m pip install --user --upgrade sigstore
        python -m pip install --user --upgrade meson
        python -m pip install --user --upgrade setuptools_scm
        python -m pip install --user --upgrade ninja
        python -m build -w
        python -m pyc_wheel dist/*.whl
        meson setup build
        meson dist -C build --formats gztar --no-tests --allow-dirty
        mv build/meson-dist/OZI-${{ steps.release.outputs.version }}.tar.gz dist/OZI-${{ steps.release.outputs.version }}.tar.gz 
        sigstore sign dist/*.whl dist/*.tar.gz
        mkdir sig
        mv dist/OZI-${{ steps.release.outputs.version }}.tar.gz.sig sig/OZI-${{ steps.release.outputs.version }}.tar.gz.sig
        mv dist/OZI-${{ steps.release.outputs.version }}.tar.gz.crt sig/OZI-${{ steps.release.outputs.version }}.tar.gz.crt
        mv dist/OZI-${{ steps.release.outputs.version }}.tar.gz.rekor sig/OZI-${{ steps.release.outputs.version }}.tar.gz.rekor
        mv dist/OZI-${{ steps.release.outputs.version }}.whl.sig sig/OZI-${{ steps.release.outputs.version }}.whl.sig
        mv dist/OZI-${{ steps.release.outputs.version }}.whl.crt sig/OZI-${{ steps.release.outputs.version }}.whl.crt
        mv dist/OZI-${{ steps.release.outputs.version }}.whl.rekor sig/OZI-${{ steps.release.outputs.version }}.whl.rekor

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      # NOTE: DO NOT wrap the conditional in ${{ }} as it will always evaluate to true.
      # See https://github.com/actions/runner/issues/1173
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
      if: steps.release.outputs.released == 'true'

    - name: Publish package distributions to GitHub Releases
      uses: python-semantic-release/upload-to-gh-release@main
      if: steps.release.outputs.released == 'true'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}