{#- OZI 0.1
# ozi/templates/pylint.pyproject.toml
# Part of the OZI Project, under the Apache License v2.0 with LLVM Exceptions.
# See LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
-#}
[tool.pylint.MASTER]
check-quote-consistency = true
expected-line-ending-format = "LF"
max-nested-blocks = 4
max-line-length = {{ spec.python.src.format.max_line_length }}
disable = "C0301"