{#- OZI 0.1
# ozi/templates/pyright.pyproject.toml
# Part of the OZI Project, under the Apache License v2.0 with LLVM Exceptions.
# See LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
-#}
[tool.pyright]
reportMissingTypeStubs = false
exclude = [ 
{%- for exclude in spec.python.lint.exclude %}
    "{{ exclude }}",
{%- endfor %}
    "tests",
]