{#- OZI 0.1
# ozi/templates/ruff.pyproject.toml
# Part of the OZI Project, under the Apache License v2.0 with LLVM Exceptions.
# See LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
-#}
[tool.ruff]
line-length = {{ spec.python.src.format.max_line_length }}
extend-exclude = [
{%- for exclude in spec.python.lint.exclude %}
    "{{ exclude }}",
{%- endfor %}
]
select = ["ALL"]
ignore = [
{%- for ignore in ozi.experimental.ruff.ignore %}
    "{{ ignore }}",
{%- endfor %}
]
# target-version = "@PYTHON_VERSION_DIST@"

[tool.ruff.lint.mccabe]
max-complexity = {{ spec.python.src.format.max_complexity }}

[tool.ruff.format]
line-ending = "{{ spec.python.src.format.line_end|lower }}"
quote-style = "{{ spec.python.src.format.quotes }}"

[tool.ruff.isort]
force-single-line = {{ spec.python.src.format.single_line_imports|lower }}

[tool.ruff.lint.pycodestyle]
{%- set x = spec.python.src.format.max_line_length|int  %}
max-line-length = {{ (x + x * 0.10)|round(method='floor')|int }}

[tool.ruff.lint.flake8-copyright]
author="{% for author in project.author %}{{ author }},{% endfor %}"

[tool.ruff.lint.flake8-quotes]
inline-quotes = "{{ spec.python.src.format.quotes }}"

[tool.ruff.lint.flake8-type-checking]
strict = true